version: "3.3"

services:
  ruby265:
    build:
      context: .
      dockerfile: Dockerfile.ruby265
    image: windmill_knight/ruby:2.6.5
    container_name: ruby265
    restart: always
    volumes:
      - /mnt/e/workspace:/root/workspace
      - /mnt/e/vendor/bundle:/root/vendor/bundle
    working_dir: /root/workspace
    command: top -b
