version: "3.3"

services:
  ruby265:
    build:
      context: .
      dockerfile: Dockerfile.rails523
    image: windmill_knight/rails:5.2.3-ruby265
    container_name: ruby265_rails523
    restart: always
    network_mode: "host"
    volumes:
      - /mnt/e/workspace:/root/workspace
      - /mnt/e/vendor/bundle:/root/vendor/bundle
      - /home/windmill_knight/.ssh:/root/.ssh
    working_dir: /root/workspace
    # ports:
    #   - "3000:3000"
    command: top -b
