version: '3.4'

services:
  docker_registry:
    image: registry
    container_name: docker_registry
    network_mode: 'host'
    restart: always
    volumes:
      - docker_images:/var/lib/registry

volumes:
  docker_images:

