version: "3.3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_DATABASE: "mysql_development"
      # MYSQL_USER: 'development'
      # MYSQL_PASS: 'development'
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

volumes:
  mysql_data:
