version: "3.4"

services:
  development_rails603_ruby265:
    build:
      context: .
      network: host
    image: 103.14.34.141:5000/sanmingzi/rails:6.0.3-development
    container_name: development_rails603_ruby265
    restart: always
    network_mode: "host"
    volumes:
      - /workspace:/workspace
      - /home/windmill_knight/.ssh:/root/.ssh
    environment:
      RAILS_SERVE_STATIC_FILES: 'true'
      SSO_DATABASE_URL: 'mysql2://root:root@127.0.0.1/sso_development'
      REDIS_CACHE_URL: 'redis://127.0.0.1:6379/0/cache'
      REDIS_SESSION_URL: 'redis://127.0.0.1:6379/0/session'
    working_dir: /workspace
    command: /bin/sh -c "top -b"
